### ISSUE TITLE
我的华硕h81m-e i7-4790求助

### ISSUE THREAD

**Issue by YiRanYouM** [VanXNF/Hackintosh-I5-4590-ASUS-H81M-D-R2.0#1]
我的台式机华硕h81m-e i7-4790 hd4600，请问你这个efi适用我的电脑吗？

**Comment by VanXNF** [comment]
> 我的台式机华硕h81m-e i7-4790 hd4600，请问你这个efi适用我的电脑吗？

不太清楚，这个机子我就搞过一次就丢家里了，想知道能不能用，你只能安装试试了，祝你好运
