### ISSUE TITLE
Serial/COM Port这个在哪里，我没找到

### ISSUE THREAD

**Issue by YiRanYouM** [VanXNF/Hackintosh-I5-4590-ASUS-H81M-D-R2.0#2]
如题

**Comment by VanXNF** [comment]
这个恐怕你得自己在bios中找了，我现在这个机子也不在身边。实在找不到不管也可以的，不会有太大影响。

**Comment by YiRanYouM** [comment]
我在bios里找了很长时间没找到串口设置；现在是我的黑苹果有一个问题，就是休眠后，按键盘唤醒后，会显示黄屏（一个苹果logo，背景是黄色的，按键盘上按键有声音），然后一会儿就会黑屏，显示无信号，我在网上查了碰到相似的问题的网友，他是关掉串口，然后就好了

**Comment by VanXNF** [comment]
找不到的话试试更新一下bios，这玩意儿我没记错的话在 bios 的 io 设置里

**Comment by YiRanYouM** [comment]
好的，谢谢

**Comment by VanXNF** [comment]
不知道你找到了没，可以看我这个，最底下两个都关了就行 ![](https://tva1.sinaimg.cn/large/008eGmZEly1gn3n3fc5hbj30zk0qo77q.jpg)

**Comment by YiRanYouM** [comment]
我的机器没有下面那2项，我更新了bios到最新的也没有，但是有了那个cfg 锁；现在更新bios后，我机器 现在都不能休眠了，黑屏后 风扇还在转，之前还可以休眠，只是醒来黑屏

**Comment by VanXNF** [comment]
> 我的机器没有下面那2项，我更新了bios到最新的也没有，但是有了那个cfg 锁；现在更新bios后，我机器 现在都不能休眠了，黑屏后 风扇还在转，之前还可以休眠，只是醒来黑屏

你的机器和我这个不是同一型号？这台机器我打 0D/6D 补丁之前也是不能休眠。

**Comment by YiRanYouM** [comment]
我的型号是H81M-E,  那个补丁 我没更新bios之前打了，现在更新了bios，不知道要不要重新打

**Comment by VanXNF** [comment]
> 我的型号是H81M-E, 那个补丁 我没更新bios之前打了，现在更新了bios，不知道要不要重新打

要打的，这个补丁针对的不是 bios，你不打就会有异常唤醒

**Comment by YiRanYouM** [comment]
我看了下0d06已经打了

**Comment by YiRanYouM** [comment]
更新bios后，我这现在是不能睡眠
